[DEFAULT]
# Used for actual test, set to "auto" to pick the first:
DEV_TEST  = auto
# Used for cloud embeddings computation, set to "auto" to pick the first:
DEV_CLOUDS = auto
WRITE_RESULTS = true

[p.bert_CC_Cap3D_prove]
# The amount of texts to consider:
N = 10
K = 25
DATASET = ./data/hard_%(N)s_among_%(K)s 
DATA_DIR = /media/data2/dmercanti/datasets
CHECKPOINT = /home/dmercanti/dev/cross_coherence_objaverse/exps/01/checkpoint_23.pth
# weights, see: https://github.com/OpenRobotLab/PointLLM/issues/1
# 661,577 samples:
# ID_TEXT_FILE = '/media/data2/dmercanti/datasets/objaverse_660K/Cap3D_automated_Objaverse.csv'
# 549,922 sAMPLES:
ID_TEXT_FILE = %(DATA_DIR)s/objaverse_660K/Cap3D_automated_Objaverse_highquality.csv
NOT_FOUND_LIST = /home/dmercanti/dev/cross_coherence_objaverse/data/not_found
# Default:
PBERT_CONFIG_FILE = /home/dmercanti/dev/PointLLM/checkpoint_point_encoder/PointTransformer_tiny_8192point.yaml
PBERT_WW = /home/dmercanti/dev/PointLLM/checkpoint_point_encoder/pointBert_ww_Tiny/checkpoint_7573.pt
POINTLLM_CODE_DIR = /home/dmercanti/dev/PointLLM/
PCs_PATH = %(DATA_DIR)s/objaverse_660K/8192_npy/
TXT_EMB_PATH = /media/data4/dmercanti/cap3D_txt_embeddings/
USE_STORED_TEXTS = True
